accounts/urls.py
from django.urls import path
from.import views

app_name = 'accounts'

urlpatterns = [
  path("signup/", views.SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('',views.index,name='index'),
    path('create',views.create,name='create'),
    path('store',views.store,name='store'),
    path('<int:id>',views.show,name='show'),
    path('edit/<int:id>',views.edit,name='edit'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('comment/<int:id>',views.comment,name='comment'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    text = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    target = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at =models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.text[:20]
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ('username', 'password1','password2')
        

blog/forms.py
from django import forms
from .models import Comment

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text'),
        labels = {'text':'コメント',}
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'class' : 'form-control',
                    'placeholder':"内容",
                    'rows': "5",
                }
            ),
        }

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy
from .forms import SignUpForm
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
import datetime as dt
from blog.models import Post,Comment
from .forms import CommentCreateForm

# 一覧表示
def index(request):
    # データの取り出し
    posts = Post.objects.all()
    # データを渡す
    context = {
        'posts': posts,
    }
    
    return render(request, 'blog/index.html',context)

# 新規投稿
def create(request):
    return render(request, 'blog/create.html')

# 登録処理
def store(request):
    # データの受け取り
    post = Post(
        title = request.POST.get('title'),
        text = request.POST.get('text'),
        user = request.user,
    )
    post.save()
    # データの保存
    # リダイレクト
    return redirect(index)

# 詳細画面
def show(request,id):
      # データの取り出し
    post = get_object_or_404(Post, pk=id)
    comments = Comment.objects.filter(target=id)
    # データを渡す
    context = {
        'post': post,
        'comments':comments
    }
    
    return render(request, 'blog/show.html',context)

# 編集更新画面
def edit(request,id):
       # データの取り出し
    post = get_object_or_404(Post, pk=id)
    # データを渡す
    context = {
        'post': post,
    }
    return render(request, 'blog/edit.html',context)

# 更新処理
def update(request,id):
    post = Post(
        pk = id,
        title = request.POST.get('title'),
        text = request.POST.get('text'),
    )
    post.save(
        update_fields=[
            'title',
            'text',
            'updated_at',
        ]
    )
    return redirect(index)


# 削除
def delete(request,id):
    post = Post.objects.get(pk=id)
    post.delete()
    return redirect(index)

#コメント
def comment(request,id):
    post = get_object_or_404(Post,pk=id)
    if request.method == 'POST':
        commentCreateForm= CommentCreateForm(request.POST)
        if commentCreateForm.is_valid():
            comment = commentCreateForm.save(commit=False) 
            comment.user=request.user
            comment.target=post
            comment.save()
            return redirect(show,id)
    else:
        commentCreateForm = CommentCreateForm()
    
    context = {
        'post' : post,
        'form' : commentCreateForm,
    }
    
    return render(request, 'blog/comment.html',context)

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}
{% block title %}登録{% endblock %}

{% block content%}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card text-center">
        <div class="card-header">
          Sign up
        </div>
        <section class='singnup-form mt-5'>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit' class="btn btn-primary mb-5">Sign up</button>
          </form>
        </section>
      </div>
    </div>
  </div>
</div>
{% endblock %}
  

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
  </head>
  <body>
    <header>
      <div class="header-left">
        <a class="navbar-brand text-dark" href="{% url 'index' %}">
          <img class="logo" src="{% static 'images/logo.png' %}" alt="">
          <span class="fs-4">SeedTech</span>
        </a>
      </div>
      <div class="header-right">
        <ul class="nav">
          <li>
            <a href="#">Seedkun</a>
          </li>
        </ul>
      </div>
    </header>
    {% block content %}
    {% endblock %}
  <footer>
    Copyright &copy; Seedkun Inc.
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/comment.html
{% extends 'layout.html' %}

{% block title %}コメント入力{% endblock title %}

{%block content%}
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-8">
      <h2>以下の記事にコメントします</h2>
      <div class="card mt-3">
        <div class="card-header">
          <h5>タイトル：{{ post.title }}</h5>
        </div>
        <div class="card-body">
          <p class="card-text">内容：{{ post.text }}</p>
          <p>投稿日時：{{ post.created_at }}</p>
          {% if post.created_at|date:"Y.m.d.h.i.s" != post.updated_at|date:"Y.m.d.h.i.s"  %}
            <p>更新日時：{{ post.updated_at }}</p>
          {% endif %}
          <p class="card-text">投稿者 : {{ post.user }}さん</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col-md-8">
      <form  method="post">
        {% csrf_token %}
        <input type="hidden" name="post_id" value="{{ post.id }}"/>
        <div class="form-group">
          
          {{ form }}
          <!-- <textarea class="form-control" placeholder="内容" rows="5" name="body"></textarea> -->
        </div>
        <button type="submit" class="btn btn-primary mt-3">コメントする</button>
      </form>
    </div>
  </div>
</div>
{% endblock content%}  

blog/templates/blog/create.html
{% extends 'layout.html' %}

{% block title %}新規投稿{% endblock title %}

{%block content%}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form action="{% url 'store' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label>タイトル</label>
          <input type="text" class="form-control" placeholder="タイトルを入力して下さい" name="title">
        </div>
        <div class="form-group mt-3">
          <label>内容</label>
          <textarea class="form-control" placeholder="内容" rows="5" name="text"></textarea>
        </div>
        <button type="submit" class="btn btn-primary mt-3">作成</button>
      </form>
    </div>
  </div>
</div>
{% endblock content%}  

blog/templates/blog/edit.html
{% extends 'layout.html' %}

{% block title %}投稿を編集{% endblock title %}

{%block content%}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card mt-3">
        <div class="card-header">
          <h5>タイトル：{{ post.title }}</h5>
        </div>
        <div class="card-body">
          <p class="card-text">内容：{{ post.text }}</p>
          <p>投稿日時：{{ post.created_at }}</p>
          <p>更新日時：{{ post.updated_at }}</p>
          <p class="card-text">投稿者 : {{ post.user }}さん</p>
        </form>
      </div>
    </div>
    <form action="{% url 'update' id=post.id %}" method="POST">
      {% csrf_token %}
      <div class="form-group mt-5">
        <label>タイトル</label>
        <input type="text" class="form-control" value="" name="title">
      </div>
      <div class="form-group mt-3">
        <label>内容</label>
        <textarea class="form-control" rows="5" name="text"></textarea>
      </div>
      <button type="submit" class="btn btn-primary mt-3">更新する</button>
    </form>
  </div>
</div>
</div>
{% endblock content%}  

blog/templates/blog/index.html
{% extends 'layout.html' %}

{% block title %}投稿一覧{% endblock title %}

{%block content%}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        {% if user.is_authenticated %}
          <div class="col-md-2 mb-2 offset-md-10 text-right">
            <a href="{% url 'create' %}" class="btn btn-primary">
              新規投稿
            </a>
          </div>
        {% endif %}
        <div class="card text-center">
          <div class="card-header">
            投稿一覧
          </div>
          
          {% for post in posts %}
            <div class="card-body">
              <h5 class="card-title">タイトル : {{ post.title }}</h5>
              <p class="card-text">
                内容 : {{ post.text }}
              </p>
              <p class="card-text">投稿者 : {{ post.user }}さん</p>
              <a href="{% url 'show' id=post.id %}" class="btn btn-primary">詳細へ</a>
            </div>
            <div class="card-footer text-muted border-top-0 border-bottom">
              投稿日時 : {{ post.updated_at|date:"Y/m/d H:i" }}
            </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
{% endblock content%}  

blog/templates/blog/show.html
{% extends 'layout.html' %}

{% block title %}投稿詳細{% endblock title %}

{%block content%}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card mt-3">
        <div class="card-header">
          <h5>タイトル：{{ post.title }}</h5>
        </div>
        <div class="card-body">
          <p class="card-text">内容：{{ post.text }}</p>
          <p>投稿日時：{{ post.created_at }}</p>

          {% if post.created_at|date:"Y.m.d.h.i.s" != post.updated_at|date:"Y.m.d.h.i.s"  %}
            <p>更新日時：{{ post.updated_at }}</p>
          {% endif %}

          <p class="card-text">投稿者 : {{ post.user }}さん</p>
          {% if user.is_authenticated %}
            {% if post.user.id == request.user.id %}
              <a href="{% url 'edit' id=post.id %}" class="btn btn-primary mt-3">編集する</a>
              <form action="{% url 'delete' id=post.id %}" method="post">
                {% csrf_token %}
                <input type='submit' value='削除' class="btn btn-danger mt-3" onclick='return confirm("本当に削除しますか？");'>
              </form>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% if user.is_authenticated %}
    <div class="row justify-content-center">
      <div class="col-md-8">
        <a href="{% url 'comment' id=post.id %}" >
          <button type="button" class="btn btn-primary mt-3">コメントする</button>
        </a>
      </div>
    </div>
  {% endif %}

  <div class="row justify-content-center">
    <div class="col-md-8 mt-5">
      コメント一覧
      {%for comment in comments %}
        <div class="card mt-3">
          <h5 class="card-header">投稿者：{{ comment.user }}</h5>
          <div class="card-body">
            <h5 class="card-title">投稿日時：{{ comment.created_at }}</h5>
            <p class="card-text">内容：{{  comment.text  }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content%}  

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

  <body>
    <header>
      <div class="header-left">
        <a class="navbar-brand text-dark" href="{% url 'index' %}">
          <img class="logo" src="{% static 'images/logo.png' %}" alt="">
          <span class="fs-4">SeedTech</span>
        </a>
      </div>
      <div class="header-right">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="nabvar-text">{{ user }}</span>
            </li>
            <li class="nav-item">
              <a href="{% url 'logout' %}" class="logout nab-link">Logout</a>
            </li>
          {%else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="logout nab-link">Login</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'accounts:signup' %}" class="logout nab-link">Sign up</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </header>

    {% block content %}{% endblock %}

    <footer>
      Copyright &copy; Seedkun Inc.
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  </body>

</html>